"""#172 — el catálogo de agentes de unidad, y el módulo `agentes` para publicarlos.

Dos tablas operacionales, como las del catálogo de funciones: el agente (de una organización, con
la unidad declarada como texto) y sus versiones (prompt, carpeta y declaración, con la revisión
posterior y la suspensión).

**El módulo no se concede a nadie aquí.** Publicar agentes es una capacidad nueva, y concederla
en bloque a quien ya tiene otro módulo sería decidir por la institución quién publica. Usarlos no
lo exige: el catálogo se ofrece a su colectivo.

Revision ID: a3c9e5f1d724
Revises: f2a8d6c3b190
Create Date: 2026-10-02 12:28:31.804405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3c9e5f1d724'
down_revision: Union[str, None] = 'f2a8d6c3b190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_agentes_unidad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('unidad', sa.String(length=200), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_agentes_unidad_organizacion_id'), 'hub_agentes_unidad', ['organizacion_id'], unique=False)
    op.create_table('hub_agente_unidad_versiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agente_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('carpeta_url', sa.String(length=2048), nullable=False),
    sa.Column('finalidad', sa.Text(), nullable=False),
    sa.Column('responsable', sa.String(length=255), nullable=False),
    sa.Column('colectivo', sa.String(length=20), nullable=False),
    sa.Column('grupos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('revision_prevista_en', sa.Date(), nullable=False),
    sa.Column('declarada_por', sa.UUID(), nullable=False),
    sa.Column('declarada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revisada_por', sa.UUID(), nullable=True),
    sa.Column('revisada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_resultado', sa.String(length=20), nullable=True),
    sa.Column('revision_nota', sa.Text(), nullable=True),
    sa.Column('suspendida_por', sa.UUID(), nullable=True),
    sa.Column('suspendida_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_suspension', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("colectivo IN ('organizacion', 'grupos')", name='ck_agente_unidad_version_colectivo'),
    sa.CheckConstraint("estado IN ('registrada', 'suspendida', 'retirada')", name='ck_agente_unidad_version_estado'),
    sa.ForeignKeyConstraint(['agente_id'], ['hub_agentes_unidad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agente_id', 'version', name='uq_agente_unidad_version')
    )
    op.create_index(op.f('ix_hub_agente_unidad_versiones_agente_id'), 'hub_agente_unidad_versiones', ['agente_id'], unique=False)
    # ### end Alembic commands ###

    op.get_bind().execute(
        sa.text(
            "INSERT INTO hub_platform_modules (code, label, vigente)"
            " VALUES ('agentes', 'Agentes de unidad', true)"
            " ON CONFLICT (code) DO NOTHING"
        )
    )


def downgrade() -> None:
    # Las concesiones del módulo caen con él: sin la fila del catálogo no darían acceso a nada.
    op.get_bind().execute(sa.text("DELETE FROM hub_module_grants WHERE module_code = 'agentes'"))
    op.get_bind().execute(sa.text("DELETE FROM hub_platform_modules WHERE code = 'agentes'"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hub_agente_unidad_versiones_agente_id'), table_name='hub_agente_unidad_versiones')
    op.drop_table('hub_agente_unidad_versiones')
    op.drop_index(op.f('ix_hub_agentes_unidad_organizacion_id'), table_name='hub_agentes_unidad')
    op.drop_table('hub_agentes_unidad')
    # ### end Alembic commands ###
