"""#213 — la versión de un agente dice si su prompt se redactó con ayuda de IA.

Como `autoria` en el catálogo de funciones: `persona` o `ia`, y lo declara quien publica. Las
versiones que ya hay las escribió una persona, que es lo que pone el valor por defecto. El CHECK va
a mano porque Alembic no detecta las restricciones de este tipo.

Revision ID: a8c5e1f3b479
Revises: f7b4d9e2a368
Create Date: 2026-10-03 17:14:30.752203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c5e1f3b479'
down_revision: Union[str, None] = 'f7b4d9e2a368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub_agente_unidad_versiones', sa.Column('autoria_prompt', sa.String(length=10), server_default='persona', nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_agente_unidad_version_autoria_prompt",
        "hub_agente_unidad_versiones",
        "autoria_prompt IN ('persona', 'ia')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_agente_unidad_version_autoria_prompt", "hub_agente_unidad_versiones", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hub_agente_unidad_versiones', 'autoria_prompt')
    # ### end Alembic commands ###
