"""#173 — el índice de los agentes de unidad: una ficha por documento, y el presupuesto.

`hub_agente_fichas` guarda la ficha y la URL, **nunca el documento**, con un vector por ficha
hecho sólo del título y el resumen. Sin índice HNSW a propósito: la selección es siempre dentro
de un agente —decenas o cientos de fichas— y un HNSW con ese filtro filtraría después de buscar.

`presupuesto_documentos` va en la declaración del agente, con 5 por defecto para los que ya hay.

Revision ID: b7d2f4a8c613
Revises: a3c9e5f1d724
Create Date: 2026-10-02 14:00:51.008237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d2f4a8c613'
down_revision: Union[str, None] = 'a3c9e5f1d724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_agente_fichas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agente_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('revision_prevista_en', sa.Date(), nullable=True),
    sa.Column('metadatos', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('version_prompt_resumen', sa.String(length=100), nullable=True),
    sa.Column('modelo_resumen', sa.String(length=100), nullable=True),
    sa.Column('huella', sa.String(length=64), nullable=False),
    sa.Column('huella_embebida', sa.String(length=64), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['hub_agentes_unidad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agente_id', 'url', name='uq_agente_ficha_url')
    )
    op.create_index(op.f('ix_hub_agente_fichas_agente_id'), 'hub_agente_fichas', ['agente_id'], unique=False)
    op.add_column('hub_agente_unidad_versiones', sa.Column('presupuesto_documentos', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hub_agente_unidad_versiones', 'presupuesto_documentos')
    op.drop_index(op.f('ix_hub_agente_fichas_agente_id'), table_name='hub_agente_fichas')
    op.drop_table('hub_agente_fichas')
    # ### end Alembic commands ###
