"""AUT.7 artefactos de salida de una funcion

Revision ID: bd93bc9196a1
Revises: e8c3f5a2b904
Create Date: 2026-09-30 09:02:02.244832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd93bc9196a1'
down_revision: Union[str, None] = 'e8c3f5a2b904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_funcion_artefactos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funcion_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=True),
    sa.Column('ejecucion_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['funcion_id'], ['hub_funciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_funcion_artefactos_ejecucion_id'), 'hub_funcion_artefactos', ['ejecucion_id'], unique=False)
    op.create_index(op.f('ix_hub_funcion_artefactos_expira_en'), 'hub_funcion_artefactos', ['expira_en'], unique=False)
    op.create_index(op.f('ix_hub_funcion_artefactos_funcion_id'), 'hub_funcion_artefactos', ['funcion_id'], unique=False)
    op.create_index(op.f('ix_hub_funcion_artefactos_organizacion_id'), 'hub_funcion_artefactos', ['organizacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hub_funcion_artefactos_organizacion_id'), table_name='hub_funcion_artefactos')
    op.drop_index(op.f('ix_hub_funcion_artefactos_funcion_id'), table_name='hub_funcion_artefactos')
    op.drop_index(op.f('ix_hub_funcion_artefactos_expira_en'), table_name='hub_funcion_artefactos')
    op.drop_index(op.f('ix_hub_funcion_artefactos_ejecucion_id'), table_name='hub_funcion_artefactos')
    op.drop_table('hub_funcion_artefactos')
    # ### end Alembic commands ###
