"""#175 — qué documentos se ofrecieron en cada consulta a un agente, y con qué puntuación.

Metadatos y nada más: ni la pregunta ni el contenido de los documentos. Lo demás de la consulta
—quién, cuándo, qué agente, para qué— va al registro de actividad, y `actividad_id` las enlaza.

Revision ID: c4e8a1f6d935
Revises: b7d2f4a8c613
Create Date: 2026-10-02 16:19:46.202162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4e8a1f6d935'
down_revision: Union[str, None] = 'b7d2f4a8c613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_agente_consultas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agente_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('ocurrido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('documentos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('actividad_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['hub_agentes_unidad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_agente_consultas_agente_id'), 'hub_agente_consultas', ['agente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hub_agente_consultas_agente_id'), table_name='hub_agente_consultas')
    op.drop_table('hub_agente_consultas')
    # ### end Alembic commands ###
