"""#175 — un agente puede esperar que quien consulta adjunte su documento en el asistente general.

Cambia el prompt: los enlaces pasan a ser el criterio con el que se analiza el adjunto. El adjunto
va directo al asistente y la plataforma no lo ve. Los agentes que ya hay no lo esperan.

Revision ID: e6a3c8d1f257
Revises: d5f9b2c7e148
Create Date: 2026-10-02 19:31:13.720660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a3c8d1f257'
down_revision: Union[str, None] = 'd5f9b2c7e148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub_agente_unidad_versiones', sa.Column('espera_adjunto', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hub_agente_unidad_versiones', 'espera_adjunto')
    # ### end Alembic commands ###
