"""#174 — el índice se mantiene solo: cuándo llegó, de dónde y cuántos documentos hay en la carpeta.

`indice_actualizado_en` se apunta en cada carga, también sin cambios: es lo que distingue un
guion vivo de uno parado. `documentos_en_carpeta` lo manda el guion para contarlos contra las
fichas. Los agentes que ya hay quedan sin fecha, que es la verdad: nadie ha mandado nada aún por
la vía nueva.

Revision ID: f7b4d9e2a368
Revises: e6a3c8d1f257
Create Date: 2026-10-03 14:00:33.637938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b4d9e2a368'
down_revision: Union[str, None] = 'e6a3c8d1f257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub_agentes_unidad', sa.Column('indice_actualizado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hub_agentes_unidad', sa.Column('indice_origen', sa.String(length=10), nullable=True))
    op.add_column('hub_agentes_unidad', sa.Column('documentos_en_carpeta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hub_agentes_unidad', 'documentos_en_carpeta')
    op.drop_column('hub_agentes_unidad', 'indice_origen')
    op.drop_column('hub_agentes_unidad', 'indice_actualizado_en')
    # ### end Alembic commands ###
